// <auto-generated />
using System;
using FAMSWPF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FAMSWPF.Migrations
{
    [DbContext(typeof(FAMSContext))]
    partial class FAMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.ContraAssets.AdvanceX", b =>
                {
                    b.Property<int>("AdvXId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MainAccount")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("MainAdvance")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("AdvXId")
                        .HasName("PK_AdvancesX");

                    b.HasIndex("MainAccount")
                        .IsUnique()
                        .HasName("IX_AdvanceX_MainAcc");

                    b.HasIndex("MainAdvance")
                        .IsUnique()
                        .HasName("IX_AdvanceX_MainAdv");

                    b.ToTable("AdvancesX","AssetsContra");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.ContraAssets.DebtorX", b =>
                {
                    b.Property<int>("DrXId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<int>("MainDebtor")
                        .HasColumnType("int");

                    b.HasKey("DrXId");

                    b.HasIndex("MainAccount")
                        .IsUnique()
                        .HasName("IX_DebtorsX_MainAcc");

                    b.HasIndex("MainDebtor")
                        .IsUnique()
                        .HasName("IX_DebtorsX_MainDebt");

                    b.ToTable("DebtorsX","AssetsContra");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.ContraAssets.LiquidSecurityX", b =>
                {
                    b.Property<int>("SecXId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<int>("MainSecurity")
                        .HasColumnType("int");

                    b.HasKey("SecXId");

                    b.HasIndex("MainAccount")
                        .IsUnique()
                        .HasName("IX_LiqSecX_MainAcc");

                    b.HasIndex("MainSecurity")
                        .IsUnique()
                        .HasName("IX_LiqSecX_MainSec");

                    b.ToTable("LiquidSecuritiesX","AssetsContra");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.ContraAssets.NonCurrentAssetX", b =>
                {
                    b.Property<int>("NCAXId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<int>("MainAsset")
                        .HasColumnType("int");

                    b.HasKey("NCAXId");

                    b.HasIndex("MainAccount")
                        .IsUnique()
                        .HasName("IX_NCAX_MainAcc");

                    b.HasIndex("MainAsset")
                        .IsUnique()
                        .HasName("IX_NCAX_MainAsset");

                    b.ToTable("NonCurrrentX","AssetsContra");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.ContraAssets.OtherCurrentAssetX", b =>
                {
                    b.Property<int>("OCAXId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<int>("MainAsset")
                        .HasColumnType("int");

                    b.HasKey("OCAXId");

                    b.HasIndex("MainAccount")
                        .IsUnique()
                        .HasName("IX_OCAX_MainAcc");

                    b.HasIndex("MainAsset")
                        .IsUnique()
                        .HasName("IX_OCAX_MainAsset");

                    b.ToTable("OtherCurrentX","AssetsContra");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.Advance", b =>
                {
                    b.Property<int>("AdvanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidUpto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("AdvanceId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("Advances","Assets");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.Debtor", b =>
                {
                    b.Property<int>("DebtorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CNIC")
                        .HasColumnName("CNIC")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("CellNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("Customer")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CustomerSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("KeyPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<string>("NTN")
                        .HasColumnName("NTN")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("PlotAddress")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("RegionAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ResidNumber")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("WorkNumber")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("DebtorId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("Debtors","Assets");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.Inventories.InventoryFinished", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("MinLevelUnits")
                        .HasColumnType("decimal(26, 10)");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("UnitSize")
                        .HasColumnType("decimal(26, 10)");

                    b.HasKey("ItemId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("FinishedGoods","Assets");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.Inventories.InventoryInProcess", b =>
                {
                    b.Property<int>("WIPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.HasKey("WIPId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("WorkInProcess","Assets");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.Inventories.InventoryRaw", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("MinLevelUnits")
                        .HasColumnType("decimal(26, 10)");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("UnitSize")
                        .HasColumnType("decimal(26, 10)");

                    b.HasKey("ItemId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("RawMaterials","Assets");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.LiquidAssets.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("BankBranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OpeningDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BankId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("BankAccounts","Assets");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.LiquidAssets.Cash", b =>
                {
                    b.Property<int>("CashId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.HasKey("CashId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("CashAccounts","Assets");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.LiquidAssets.LiquidSecurity", b =>
                {
                    b.Property<int>("SecurityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<string>("Serials")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<DateTime?>("Since")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("SecurityId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("LiquidSecurities","Assets");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.OtherCurrentAsset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.HasKey("AssetId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("OtherCurrent","Assets");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.NonCurrentAssets.Furniture", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainNCA")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("AssetId");

                    b.HasIndex("MainNCA")
                        .IsUnique();

                    b.ToTable("FurnitureFixtures","Assets");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.NonCurrentAssets.Machinery", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Capacity")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MachineTyp")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("MainNCA")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("MachineId");

                    b.HasIndex("MainNCA")
                        .IsUnique();

                    b.ToTable("MachinesEquips","Assets");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.NonCurrentAssets.NonCurrentAsset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("DepreciationRate")
                        .HasColumnType("decimal(26, 10)");

                    b.Property<string>("DepreciationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<decimal>("LifeYears")
                        .HasColumnType("decimal(26, 10)");

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<bool>("New")
                        .HasColumnType("bit");

                    b.Property<decimal>("OriginalCost")
                        .HasColumnType("decimal(26, 10)");

                    b.Property<DateTime>("PurchDt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ScrapValue")
                        .HasColumnType("decimal(26, 10)");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("AssetId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("NonCurrentAssets","Assets");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.NonCurrentAssets.OtherNonCurrent", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("MainNCA")
                        .HasColumnName("MainNCA")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("AssetId");

                    b.HasIndex("MainNCA")
                        .IsUnique();

                    b.ToTable("OtherNonCurrent","Assets");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.NonCurrentAssets.RealEstate", b =>
                {
                    b.Property<int>("EstateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AreaSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MainNCA")
                        .HasColumnType("int");

                    b.Property<string>("PlotAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("RegionAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("EstateId");

                    b.HasIndex("MainNCA")
                        .IsUnique();

                    b.ToTable("RealEstates","Assets");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.NonCurrentAssets.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Capacity")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MainNCA")
                        .HasColumnName("MainNCA")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Manufucturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("RegNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("VehicleId");

                    b.HasIndex("MainNCA")
                        .IsUnique();

                    b.ToTable("Vehicles","Assets");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Equity.Capital", b =>
                {
                    b.Property<int>("CapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CNIC")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("CellNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("KeyPerson")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<string>("NTN")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("OwnerSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlotAddress")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("RegionAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ResidNumber")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<double>("ShareRatio")
                        .HasColumnType("float");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("WorkNumber")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("CapId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("Capital","Capital");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Equity.Contra.CapitalX", b =>
                {
                    b.Property<int>("CapXId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<int>("MainCapital")
                        .HasColumnType("int");

                    b.HasKey("CapXId");

                    b.HasIndex("MainAccount")
                        .IsUnique()
                        .HasName("IX_CapitalX_MainAcc");

                    b.HasIndex("MainCapital")
                        .IsUnique()
                        .HasName("IX_CapitalX_Capital");

                    b.ToTable("CapitalX","CapitalContra");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Expenditure.Contra.MainCostX", b =>
                {
                    b.Property<int>("CostXId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<int>("MainCost")
                        .HasColumnType("int");

                    b.HasKey("CostXId");

                    b.HasIndex("MainAccount")
                        .IsUnique()
                        .HasName("IX_MainCostX_MainAcc");

                    b.HasIndex("MainCost")
                        .IsUnique()
                        .HasName("IX_MainCostX_Cost");

                    b.ToTable("MainCostX","ExpenditureContra");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Expenditure.Contra.OtherExpenseX", b =>
                {
                    b.Property<int>("ExpXId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<int>("MainExpense")
                        .HasColumnType("int");

                    b.HasKey("ExpXId");

                    b.HasIndex("MainAccount")
                        .IsUnique()
                        .HasName("IX_OtherExpX_MainAcc");

                    b.HasIndex("MainExpense")
                        .IsUnique()
                        .HasName("IX_OtherExpX_Expense");

                    b.ToTable("OtherExpenseX","ExpenditureContra");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Expenditure.DirectLabour", b =>
                {
                    b.Property<int>("DLId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Labourer")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LbrrAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LbrrContact")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.HasKey("DLId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("DirectLabour","Expenditure");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Expenditure.MainCost", b =>
                {
                    b.Property<int>("CostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CostScheme")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.HasKey("CostId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("MainCost","Expenditure");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Expenditure.OtherExpense", b =>
                {
                    b.Property<int>("ExpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExpScheme")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.HasKey("ExpId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("OtherExpense","Expenditure");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Foundation.AccountNature", b =>
                {
                    b.Property<string>("NatureId")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<bool>("DebitNature")
                        .HasColumnType("bit");

                    b.Property<string>("NatureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("NatureId");

                    b.HasIndex("NatureName")
                        .IsUnique()
                        .HasName("IX_AccountsNatures");

                    b.ToTable("AccountNature","Foundation");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Foundation.Currency", b =>
                {
                    b.Property<string>("CurrencyId")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<decimal?>("ConvertRatio")
                        .HasColumnType("numeric(18, 9)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("SinceWhen")
                        .HasColumnType("datetime2");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currency","Foundation");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Foundation.MainAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("NatureId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("AccountId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("NatureId");

                    b.ToTable("MainAccount","Foundation");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Journals.GJItem", b =>
                {
                    b.Property<int>("GTAccId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("DrCr")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<int>("MainTranx")
                        .HasColumnType("int");

                    b.HasKey("GTAccId");

                    b.HasIndex("MainAccount");

                    b.HasIndex("MainTranx");

                    b.ToTable("GeneralJournalItems","Transactions");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Journals.GeneralJournal", b =>
                {
                    b.Property<int>("GenTranxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TranxDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GenTranxId");

                    b.ToTable("GeneralJournal","Transactions");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Liabilities.CurrentLiabilities.Accrual", b =>
                {
                    b.Property<int>("AccrualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<string>("Payee")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("AccrualId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("Accruals","Liabilities");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Liabilities.CurrentLiabilities.Creditor", b =>
                {
                    b.Property<int>("CrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CNIC")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("CellNumber")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("KeyPerson")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<string>("NTN")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("PlotAddress")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("RegionAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ResidNumber")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<DateTime?>("Since")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("Supplier")
                        .HasColumnType("bit");

                    b.Property<string>("WorkNumber")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("CrId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("Creditors","Liabilities");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Liabilities.CurrentLiabilities.UnearnedIncome", b =>
                {
                    b.Property<int>("UIncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Income")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.HasKey("UIncId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("UnearnedIncomes","Liabilities");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Liabilities.NonCurrentLiabilities.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AnnualRate")
                        .HasColumnType("decimal(26, 10)");

                    b.Property<string>("Lender")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Term")
                        .HasColumnType("decimal(26, 10)");

                    b.HasKey("LoanId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("Loans","Liabilities");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Liabilities.NonCurrentLiabilities.NonCurrentLiability", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AnnualRate")
                        .HasColumnType("decimal(26, 10)");

                    b.Property<string>("Lender")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Term")
                        .HasColumnType("decimal(26, 10)");

                    b.HasKey("LoanId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("NonCurrent","Liabilities");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Revenue.Contra.MainRevenueX", b =>
                {
                    b.Property<int>("RevXId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<int>("MainRevenue")
                        .HasColumnType("int");

                    b.HasKey("RevXId");

                    b.HasIndex("MainAccount")
                        .IsUnique()
                        .HasName("IX_MainRevX_MainAcc");

                    b.HasIndex("MainRevenue")
                        .IsUnique()
                        .HasName("IX_MainRevX_Revenue");

                    b.ToTable("MainRevenueX","RevenueContra");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Revenue.Contra.OtherRevenueX", b =>
                {
                    b.Property<int>("RevXId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<int>("MainRevenue")
                        .HasColumnType("int");

                    b.HasKey("RevXId");

                    b.HasIndex("MainAccount")
                        .IsUnique()
                        .HasName("IX_OtherRevX_MainAcc");

                    b.HasIndex("MainRevenue")
                        .IsUnique()
                        .HasName("IX_OtherRevX_Revenue");

                    b.ToTable("OtherRevenueX","RevenueContra");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Revenue.MainRevenue", b =>
                {
                    b.Property<int>("RevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<string>("RevenueScheme")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("RevId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("MainRevenue","Revenue");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Revenue.OtherRevenue", b =>
                {
                    b.Property<int>("RevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MainAccount")
                        .HasColumnType("int");

                    b.Property<string>("RevScheme")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("RevId");

                    b.HasIndex("MainAccount")
                        .IsUnique();

                    b.ToTable("OtherRevenue","Revenue");
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.ContraAssets.AdvanceX", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("AdvanceX")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.ContraAssets.AdvanceX", "MainAccount")
                        .HasConstraintName("FK_AdvancesX_MainAcc_MainAcc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FAMSWPF.Library.Models.Assets.CurrentAssets.Advance", "MainAdvWhich")
                        .WithOne("AdvanceX")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.ContraAssets.AdvanceX", "MainAdvance")
                        .HasConstraintName("FK_AdvancesX_Advances_MainAdv")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.ContraAssets.DebtorX", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("DebtorX")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.ContraAssets.DebtorX", "MainAccount")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FAMSWPF.Library.Models.Assets.CurrentAssets.Debtor", "MainDebtorWhich")
                        .WithOne("DebtorX")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.ContraAssets.DebtorX", "MainDebtor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.ContraAssets.LiquidSecurityX", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("LiquidSecurityX")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.ContraAssets.LiquidSecurityX", "MainAccount")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FAMSWPF.Library.Models.Assets.CurrentAssets.LiquidAssets.LiquidSecurity", "MainLiqSecWhich")
                        .WithOne("LiquidSecurityX")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.ContraAssets.LiquidSecurityX", "MainSecurity")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.ContraAssets.NonCurrentAssetX", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("NCAXMainAccWhich")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.ContraAssets.NonCurrentAssetX", "MainAccount")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAssetWhich")
                        .WithOne("NCAXMainAssetWhich")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.ContraAssets.NonCurrentAssetX", "MainAsset")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.ContraAssets.OtherCurrentAssetX", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("OCAXMainAccWhich")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.ContraAssets.OtherCurrentAssetX", "MainAccount")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAssetWhich")
                        .WithOne("OCAXMainAssetWhich")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.ContraAssets.OtherCurrentAssetX", "MainAsset")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.Advance", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("Advance")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.CurrentAssets.Advance", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.Debtor", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("Debtor")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.CurrentAssets.Debtor", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.Inventories.InventoryFinished", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("FinishedGood")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.CurrentAssets.Inventories.InventoryFinished", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.Inventories.InventoryInProcess", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("WorkInProcess")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.CurrentAssets.Inventories.InventoryInProcess", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.Inventories.InventoryRaw", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("RawMaterial")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.CurrentAssets.Inventories.InventoryRaw", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.LiquidAssets.Bank", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("BankAccount")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.CurrentAssets.LiquidAssets.Bank", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.LiquidAssets.Cash", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("CashAccount")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.CurrentAssets.LiquidAssets.Cash", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.LiquidAssets.LiquidSecurity", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("LiquidSecurity")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.CurrentAssets.LiquidAssets.LiquidSecurity", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.CurrentAssets.OtherCurrentAsset", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("OtherCurrent")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.CurrentAssets.OtherCurrentAsset", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.NonCurrentAssets.Furniture", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Assets.NonCurrentAssets.NonCurrentAsset", "MainNCAWhich")
                        .WithOne("Furniture")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.NonCurrentAssets.Furniture", "MainNCA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.NonCurrentAssets.Machinery", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Assets.NonCurrentAssets.NonCurrentAsset", "MainNCAWhich")
                        .WithOne("Machinery")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.NonCurrentAssets.Machinery", "MainNCA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.NonCurrentAssets.NonCurrentAsset", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("NonCurrentAsset")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.NonCurrentAssets.NonCurrentAsset", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.NonCurrentAssets.OtherNonCurrent", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Assets.NonCurrentAssets.NonCurrentAsset", "MainNCAWhich")
                        .WithOne("OtherNCA")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.NonCurrentAssets.OtherNonCurrent", "MainNCA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.NonCurrentAssets.RealEstate", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Assets.NonCurrentAssets.NonCurrentAsset", "MainNCAWhich")
                        .WithOne("RealEstate")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.NonCurrentAssets.RealEstate", "MainNCA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Assets.NonCurrentAssets.Vehicle", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Assets.NonCurrentAssets.NonCurrentAsset", "MainNCAWhich")
                        .WithOne("Vehicle")
                        .HasForeignKey("FAMSWPF.Library.Models.Assets.NonCurrentAssets.Vehicle", "MainNCA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Equity.Capital", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("Capital")
                        .HasForeignKey("FAMSWPF.Library.Models.Equity.Capital", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Equity.Contra.CapitalX", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("CapitalX")
                        .HasForeignKey("FAMSWPF.Library.Models.Equity.Contra.CapitalX", "MainAccount")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FAMSWPF.Library.Models.Equity.Capital", "MainCapitalWhich")
                        .WithOne("CapitalX")
                        .HasForeignKey("FAMSWPF.Library.Models.Equity.Contra.CapitalX", "MainCapital")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Expenditure.Contra.MainCostX", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("MainCostX")
                        .HasForeignKey("FAMSWPF.Library.Models.Expenditure.Contra.MainCostX", "MainAccount")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FAMSWPF.Library.Models.Expenditure.MainCost", "MainCostWhich")
                        .WithOne("MainCostX")
                        .HasForeignKey("FAMSWPF.Library.Models.Expenditure.Contra.MainCostX", "MainCost")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Expenditure.Contra.OtherExpenseX", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("OtherExpenseX")
                        .HasForeignKey("FAMSWPF.Library.Models.Expenditure.Contra.OtherExpenseX", "MainAccount")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FAMSWPF.Library.Models.Expenditure.OtherExpense", "MainExpWhich")
                        .WithOne("OtherExpenseX")
                        .HasForeignKey("FAMSWPF.Library.Models.Expenditure.Contra.OtherExpenseX", "MainExpense")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Expenditure.DirectLabour", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("DirectLabour")
                        .HasForeignKey("FAMSWPF.Library.Models.Expenditure.DirectLabour", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Expenditure.MainCost", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("MainCost")
                        .HasForeignKey("FAMSWPF.Library.Models.Expenditure.MainCost", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Expenditure.OtherExpense", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("OtherExpense")
                        .HasForeignKey("FAMSWPF.Library.Models.Expenditure.OtherExpense", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Foundation.MainAccount", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.Currency", "CurrencyWhich")
                        .WithMany("MainAccounts")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FAMSWPF.Library.Models.Foundation.AccountNature", "AccNatWhich")
                        .WithMany("MainAccounts")
                        .HasForeignKey("NatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Journals.GJItem", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithMany("GJItems")
                        .HasForeignKey("MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FAMSWPF.Library.Models.Journals.GeneralJournal", "MainTranxWhich")
                        .WithMany("GJItems")
                        .HasForeignKey("MainTranx")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Liabilities.CurrentLiabilities.Accrual", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("Accrual")
                        .HasForeignKey("FAMSWPF.Library.Models.Liabilities.CurrentLiabilities.Accrual", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Liabilities.CurrentLiabilities.Creditor", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("Creditor")
                        .HasForeignKey("FAMSWPF.Library.Models.Liabilities.CurrentLiabilities.Creditor", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Liabilities.CurrentLiabilities.UnearnedIncome", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("UnearnedIncome")
                        .HasForeignKey("FAMSWPF.Library.Models.Liabilities.CurrentLiabilities.UnearnedIncome", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Liabilities.NonCurrentLiabilities.Loan", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("Loan")
                        .HasForeignKey("FAMSWPF.Library.Models.Liabilities.NonCurrentLiabilities.Loan", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Liabilities.NonCurrentLiabilities.NonCurrentLiability", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("NonCurrentLiability")
                        .HasForeignKey("FAMSWPF.Library.Models.Liabilities.NonCurrentLiabilities.NonCurrentLiability", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Revenue.Contra.MainRevenueX", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("MainRevenueX")
                        .HasForeignKey("FAMSWPF.Library.Models.Revenue.Contra.MainRevenueX", "MainAccount")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FAMSWPF.Library.Models.Revenue.MainRevenue", "MainRevWhich")
                        .WithOne("MainRevenueX")
                        .HasForeignKey("FAMSWPF.Library.Models.Revenue.Contra.MainRevenueX", "MainRevenue")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Revenue.Contra.OtherRevenueX", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("OtherRevenueX")
                        .HasForeignKey("FAMSWPF.Library.Models.Revenue.Contra.OtherRevenueX", "MainAccount")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FAMSWPF.Library.Models.Revenue.OtherRevenue", "MainRevWhich")
                        .WithOne("OtherRevenueX")
                        .HasForeignKey("FAMSWPF.Library.Models.Revenue.Contra.OtherRevenueX", "MainRevenue")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Revenue.MainRevenue", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("MainRevenue")
                        .HasForeignKey("FAMSWPF.Library.Models.Revenue.MainRevenue", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAMSWPF.Library.Models.Revenue.OtherRevenue", b =>
                {
                    b.HasOne("FAMSWPF.Library.Models.Foundation.MainAccount", "MainAccWhich")
                        .WithOne("OtherRevenue")
                        .HasForeignKey("FAMSWPF.Library.Models.Revenue.OtherRevenue", "MainAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
